services:
  mysql:
    image: mysql
    env_file:
<<<<<<< HEAD
    - .env
=======
      - .env
>>>>>>> 0beb0221b96fd05b2b29868e2eb9cd232bd87e2d
    restart: always
    container_name: mysql_hospital
    environment:
      MYSQL_DATABASE: 'hospital'
      MYSQL_ROOT_PASSWORD: 'endocKbOsIQU'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
<<<<<<< HEAD

=======
>>>>>>> 0beb0221b96fd05b2b29868e2eb9cd232bd87e2d
